# Generated by Django 6.0.2 on 2026-02-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
